### ISSUE TITLE
出入校理由和地点增加配置

### ISSUE THREAD

**Issue by ysmintor** [yzs981130/autoSubmit#2]
要都一样的话，过滤出来太容易了，另外申报的时间也设置。说明里提示下？go 没学过，改起来稍费劲。

**Comment by yzs981130** [comment]
出校理由：https://github.com/yzs981130/autoSubmit/blob/1dc9d2b53206568d2493904dc62d58b8a8271e5c/main.go#L252

出校轨迹：https://github.com/yzs981130/autoSubmit/blob/1dc9d2b53206568d2493904dc62d58b8a8271e5c/main.go#L256

入校理由：https://github.com/yzs981130/autoSubmit/blob/1dc9d2b53206568d2493904dc62d58b8a8271e5c/main.go#L333

直接改引号内内容即可，等我有空改一下变为传参可配置


每天提交时间在actions的yaml里：https://github.com/yzs981130/autoSubmit/blob/1dc9d2b53206568d2493904dc62d58b8a8271e5c/.github/workflows/go.yml#L9 格式是Linux的cron，可以自行修改

**Comment by ysmintor** [comment]
所以是出入校同时申报？

**Comment by yzs981130** [comment]
> 出入校同时申报可能不太妥。
> 不知 cron 是否可以设置两个，依据运行时间判断。
> 可用性还是很强！！

感觉最简单的方式是跑两遍，上午一遍下午一遍，然后在code里面判断上午还是下午每次只填报一个，缺点是如果本地运行可能比较麻烦，但是也可以在code里面判断是否在CI中运行，可以实现一哈

**Comment by yzs981130** [comment]
> 出入校同时申报可能不太妥。
> 不知 cron 是否可以设置两个，依据运行时间判断。
> 可用性还是很强！！

分拆了一个单独的 #3

**Comment by ysmintor** [comment]
> > 出入校同时申报可能不太妥。
> > 不知 cron 是否可以设置两个，依据运行时间判断。
> > 可用性还是很强！！
> 
> 分拆了一个单独的 #3

可配置 arguments 在 github action 方式也可行？来个 feature ，从数组里随机，不然每一天的理由都一样

**Comment by yzs981130** [comment]
> > > 出入校同时申报可能不太妥。
> > > 不知 cron 是否可以设置两个，依据运行时间判断。
> > > 可用性还是很强！！
> > 
> > 
> > 分拆了一个单独的 #3
> 
> 可配置 arguments 在 github action 方式也可行？来个 feature ，从数组里随机，不然每一天的理由都一样

需要手动修改actions的yaml，将 https://github.com/yzs981130/autoSubmit/blob/29333f699f00c592d42aeb4f943ed614d5f55b10/.github/workflows/go.yml#L34 run后命令修改为类似`./autosubmit -username=1900012345 -password=dashabi -reason "玩" -track "康博斯-CBD-公主楼"`

有灵感吗？我枯竭了.jpg

**Comment by ysmintor** [comment]
> > > > 出入校同时申报可能不太妥。
> > > > 不知 cron 是否可以设置两个，依据运行时间判断。
> > > > 可用性还是很强！！
> > > 
> > > 
> > > 分拆了一个单独的 #3
> > 
> > 
> > 可配置 arguments 在 github action 方式也可行？来个 feature ，从数组里随机，不然每一天的理由都一样
> 
> 需要手动修改actions的yaml，将
> 
> https://github.com/yzs981130/autoSubmit/blob/29333f699f00c592d42aeb4f943ed614d5f55b10/.github/workflows/go.yml#L34
> 
> run后命令修改为类似`./autosubmit -username=1900012345 -password=dashabi -reason "玩" -track "康博斯-CBD-公主楼"`
> 有灵感吗？我枯竭了.jpg

哇，太有灵感了，打算在 initFlag 中像`*username = os.Getenv("USERNAME")`，写在 secrets 里。再写个 random 取数组里的原因，计划有时间学下 golang，有推荐极快速入门的书吗？

**Comment by yzs981130** [comment]
> 出入校同时申报可能不太妥。
> 不知 cron 是否可以设置两个，依据运行时间判断。
> 可用性还是很强！！

https://github.com/yzs981130/autoSubmit/tree/feat/separate 可以看下是不是符合需求的，可以在 #3 中讨论

**Comment by yzs981130** [comment]
> > > > > 出入校同时申报可能不太妥。
> > > > > 不知 cron 是否可以设置两个，依据运行时间判断。
> > > > > 可用性还是很强！！
> > > > 
> > > > 
> > > > 分拆了一个单独的 #3
> > > 
> > > 
> > > 可配置 arguments 在 github action 方式也可行？来个 feature ，从数组里随机，不然每一天的理由都一样
> > 
> > 
> > 需要手动修改actions的yaml，将
> > https://github.com/yzs981130/autoSubmit/blob/29333f699f00c592d42aeb4f943ed614d5f55b10/.github/workflows/go.yml#L34
> > 
> > run后命令修改为类似`./autosubmit -username=1900012345 -password=dashabi -reason "玩" -track "康博斯-CBD-公主楼"`
> > 有灵感吗？我枯竭了.jpg
> 
> 哇，太有灵感了，打算在 initFlag 中像`*username = os.Getenv("USERNAME")`，写在 secrets 里。�再写个 random 取数组里的原因，计划有时间学下 golang，有推荐极快速入门的书吗？

基本语法比较简单，直接搜搜就会了
