### ISSUE TITLE
根据时间一天两次分别填报出入校

### ISSUE THREAD

**Issue by yzs981130** [yzs981130/autoSubmit#3]
#2 中有需求，希望支持一天两个时间分开填报出入校

_Originally posted by @ysmintor in https://github.com/yzs981130/autoSubmit/issues/2#issuecomment-712010132_

- [ ] 分拆出校填报和入校填报
- [ ] 根据当前时间自动做出校或入校
- [ ] 修改CI支持每天两次运行
- [ ] 保持本地运行的行为不变，仅修改CI中的行为

努力不鸽，welcome PR

**Comment by ysmintor** [comment]
谢谢，上午和下午判断看了下依据 local time 和12来比较。cron 那里好像是可以用一个就实现，大概是 0 8,14 * * * 这样的形式。
我晚点merge 测试下。

**Comment by yzs981130** [comment]
> 谢谢，上午和下午判断看了下依据 local time 和12来比较。cron 那里好像是可以用一个就实现，大概是 0 8,14 * * * 这样的形式。
> 我晚点merge 测试下。

啊对对对，暴露了我不会写cron（跑
